builds:
  - id: synology-notifications
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
dockers:
- image_templates:
  - "ryancurrah/synology-notifications:{{ .Version }}-amd64"
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "ryancurrah/synology-notifications:{{ .Version }}-arm64v8"
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: ryancurrah/synology-notifications:{{ .Version }}
    image_templates:
      - ryancurrah/synology-notifications:{{ .Version }}-amd64
      - ryancurrah/synology-notifications:{{ .Version }}-arm64v8
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
